# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userPassword
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./logs:/var/log/postgres
    ports:
      - '5432:5432'
volumes:
  postgres:
